version: '3'
services:
# Rabbit service. See https://hub.docker.com/_/rabbitmq/ 
  rabbit:  
    container_name: dev-rabbit
    image:  rabbitmq:3-management
    environment:
     - RABBITMQ_DEFAULT_USER=rabbit
     - RABBITMQ_DEFAULT_PASS=mq
    ports:
     - "4369:4369"
     - "5671:5671"
     - "5672:5672"
     - "15672:15672"
     - "8080:8080"